### ISSUE TITLE
Losing results in play mode

### ISSUE THREAD

**Issue by oliverhoodoo** [laurenth-unity/LODLightmapScripts#1]
Everything seems to work good in the scene view, but once hitting play I lose the lightmap transfer, back to scene view and it returns.

2018.4 LTS.

**Comment by BitCakeStudio** [comment]
We're having the same issue on 2018.4.5f1, is there any way this could be fixed? This script is amazing other than this issue :/

**Comment by laurenth-personal** [comment]
Hi I'm sorry I didn't reply earlier. Is the object you're using this on included in static batching ? This could cause the issue because if so, objects get combined and their UVs  change.
